version: "3.8"

services:
  poc-postgres:
    image: postgres:15-alpine
    container_name: poc-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  poc-mongo:
    image: mongo:6.0
    container_name: poc-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  poc-redis:
    image: redis:7-alpine
    container_name: poc-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
  mongodata:
